version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - '${DB_MYSQL_PORT_C}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_MYSQL_DB_NAME}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
    container_name: ts-rest-server
    volumes:
      - ./mysql/data:/var/lib/mysql
